import { jsPDF } from "jspdf";

export const saveSystemOverviewPdf = () => {
  const doc = new jsPDF({ unit: "pt", format: "letter" });

  doc.setFontSize(20);
  doc.text("Teacher Transfer Management System", 40, 60);

  doc.setFontSize(12);
  doc.text("A printable summary of TTMS features and roles.", 40, 90);

  const content = [
    "Overview:",
    "- Manage teachers, schools, woredas, and transfer requests.",
    "- Role-based access for admins, MERSU officers, school directors, and teachers.",
    "- Export reports and transfer summaries as PDF.",
    "",
    "Key Features:",
    "- Teacher Management",
    "- School and Woreda Administration",
    "- Transfer Request Workflow",
    "- User Management and Permissions",
    "- PDF export for reports and summaries",
  ];

  doc.setFontSize(14);
  let y = 120;
  content.forEach((line) => {
    doc.text(line, 40, y);
    y += 20;
  });

  doc.setFontSize(12);
  doc.text("Generated by TTMS.", 40, y + 20);

  doc.save("ttms-overview.pdf");
};
